git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  showFileTree: false
  showNumstatInFilesView: true
  nerdFontsVersion: '2'
  showDivergenceFromBaseBranch: arrowAndNumber
