#!/usr/bin/env bash

source "$HOME/.config/sketchybar/variables.sh" # Loads all defined colors

# General bar and defaults

sketchybar --bar height=30 \
	color="$THM_BASE" \
	shadow="$SHADOW" \
    border_width="$BAR_BORDER_WIDTH" \
    border_color="$THM_SURFACE_1" \
	position=top \
	sticky=on \
	padding_right=3 \
	padding_left=5 \
	corner_radius="$BAR_CORNER_RADIUS" \
	y_offset=4 \
	margin=7 \
	blur_radius=0 \
	notch_width=200 \
	--default updates=when_shown \
	icon.font="$FONT:Bold:13.5" \
	icon.color="$ICON_COLOR" \
	icon.padding_left="$PADDINGS" \
	icon.padding_right="$PADDINGS" \
	label.font="$FONT:Bold:13.0" \
	label.color="$LABEL_COLOR" \
	label.padding_left="$PADDINGS" \
	label.padding_right="$PADDINGS" \
	background.padding_right="$PADDINGS" \
	background.padding_left="$PADDINGS" \
    background.border_width="$BORDER_WIDTH" \
    background.border_color="$THM_ROSEWATER"

# Left
# source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/ram.sh"
source "$ITEM_DIR/cpu.sh"
# source "$ITEM_DIR/spotify.sh"

#################### Finalizing Setup ####################

sketchybar --hotload true
sketchybar --update
echo "sketchybar configuration loaded.."
