#!/usr/bin/env sh

TRANSPARENT=0x00000000

# Color Palette
# catppuccin
# THM_BG=0xff1e1e2e
THM_BG=$TRANSPARENT
THM_ROSEWATER=0xfff5e0dc
THM_FLAMINGO=0xfff2cdcd
THM_ROSEWATER=0xfff5e0dc
THM_PINK=0xfff5c2e7
THM_MAUVE=0xffcba6f7
THM_RED=0xfff38ba8
THM_MAROON=0xffeba0ac
THM_PEACH=0xfffab387
THM_YELLOW=0xfff9e2af
THM_GREEN=0xffa6e3a1
THM_TEAL=0xff94e2d5
THM_SKY=0xff89dceb
THM_SAPPHIRE=0xff74c7ec
THM_BLUE=0xff89b4fa
THM_LAVENDER=0xffb4befe

# # General bar colors
# ICON_COLOR=$WHITE  # Color of all icons
# LABEL_COLOR=$WHITE # Color of all labels
ITEM_BG_COLOR=0xff1e1e2e

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="MesloLGS NF"

PADDINGS=3

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11
POPUP_BACKGROUND_COLOR=$BLACK
POPUP_BORDER_COLOR=$COMMENT

CORNER_RADIUS=15

# RIGHT_ITEM_PADDING_RIGHT=10
# LEFT_ITEM_PADDING_LEFT=10
# BORDER_WIDTH=1
RIGHT_ITEM_PADDING_RIGHT=8
LEFT_ITEM_PADDING_LEFT=8
BORDER_WIDTH=0

SHADOW=on
